server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: rdt-backend
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rdt_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: rdt
    password: rdt@2026!
  flyway:
    baseline-on-migrate: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.rdt.auth.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    com.rdt: DEBUG
